name: Projeto de login

on:
  push:
    branches:
      - main

jobs:
  build-e-testar:
    name: Build e Testes da Aplicação
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Build da imagem do Frontend
        run: docker build -t minha_front ./frontend

      - name: Build da imagem do Backend
        run: docker build -t minha_backend ./Backend
